"""Add username column to users table

Revision ID: 0f9eddd7f38b
Revises: fa85d4844cb1
Create Date: 2025-04-01 13:56:43.021479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9eddd7f38b'
down_revision = 'fa85d4844cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))  # Allow NULL temporarily
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
